spring:
  application:
    name: tenpo
    version: '@project.version@'
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tenpo-db
    username: tenpo
    password: tenpo


server:
  port: 8083

cache:
  ttl: 30 #ttl in minutes

retry:
  maxAttempts: 2
  maxDelay: 100

rest:
  client:
    default:
      timeout: 30

service:
  should-be-mocked: true
  uri: "http://totally-a-normal.endpoint/"


springdoc:
  show-actuator: 'false'
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
