spring:
  application:
    name: tenpo
    version: '@project.version@'
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tenpo-db
    username: tenpo
    password: tenpo


server:
  port: 8083

cache:
  ttl: 100000

retry:
  maxAttempts: 2
  maxDelay: 100

rest:
  client:
    default:
      timeout: 30

service:
  should-be-mocked: false
  uri: "http://totally-a-normal.endpoint/"